sudo: false
dist: trusty

language: scala

scala:
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8

addons:
  hosts:
    - scala-url-builder
  hostname: scala-url-builder

jobs:
  include:
    - stage: coveralls
      script: sbt coverage test coverageReport coveralls
      scala: 2.12.2
      jdk: oraclejdk8
