sudo: false
dist: trusty

language: scala

scala:
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

addons:
  hosts:
    - scala-url-builder
  hostname: scala-url-builder

script: sbt clean coverage test
jobs:
  include:
    - stage: coveralls
      script: sbt coverageReport coveralls
      scala: 2.12.2
      jdk: oraclejdk8
matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.2
      jdk: oraclejdk7
    - scala: 2.12.2
      jdk: openjdk7
